// LeadOS — توليد manifest المهارات: skills/discovery/*/SKILL.md → src/lib/skills/manifest.generated.ts
// بيتنفذ في كل build (vercel-build) — فالمحتوى يسافر جوه الباندل بدون قراءة fs وقت التشغيل.
// أي SKILL.md جديد في skills/discovery/ يتكشّف تلقائيًا مع الـbuild الجاي.
import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from "fs"
import { join } from "path"

const ROOT = join(process.cwd(), "skills", "discovery")
const OUT = join(process.cwd(), "src", "lib", "skills", "manifest.generated.ts")

const files: Array<{ path: string; content: string }> = []
if (existsSync(ROOT)) {
  for (const dir of readdirSync(ROOT).sort()) {
    const dirPath = join(ROOT, dir)
    if (!statSync(dirPath).isDirectory()) continue
    const skillPath = join(dirPath, "SKILL.md")
    if (!existsSync(skillPath)) continue
    files.push({ path: `skills/discovery/${dir}/SKILL.md`, content: readFileSync(skillPath, "utf8") })
  }
}

const header = `// AUTO-GENERATED by scripts/gen-skills-manifest.ts — متعدلش الملف ده باليد
// المصدر: skills/discovery/*/SKILL.md (${files.length} مهارة)
export const SKILL_FILES: Array<{ path: string; content: string }> = ${JSON.stringify(files, null, 2)}
`
writeFileSync(OUT, header, "utf8")
console.log(`skills manifest: ${files.length} skills → src/lib/skills/manifest.generated.ts`)
